CREATE TABLE `code_helper_session` (
  `id` bigint NOT NULL COMMENT '主键',
  `ext` varchar(2000) DEFAULT NULL,
  `remark` varchar(1000) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `version` int DEFAULT NULL,
  `session_code` varchar(64) NOT NULL COMMENT '会话编码',
  `session_name` varchar(128) DEFAULT NULL COMMENT '会话名称',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `owner_user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `owner_user_name` varchar(128) DEFAULT NULL COMMENT '用户名',
  `workspace_path` varchar(512) NOT NULL COMMENT '工作区路径',
  `project_name` varchar(128) DEFAULT NULL COMMENT '项目名称',
  `branch_name` varchar(128) DEFAULT NULL COMMENT '分支名称',
  `task_description` varchar(2000) DEFAULT NULL COMMENT '任务描述',
  `model_code` varchar(128) DEFAULT NULL COMMENT '模型编码',
  `session_status` varchar(32) DEFAULT NULL COMMENT '会话状态',
  `summary_snapshot` text COMMENT '摘要快照',
  `allowed_commands_json` text COMMENT '允许命令JSON',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code_helper_session_code_tenant` (`session_code`, `tenant_id`),
  KEY `idx_code_helper_session_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='代码助手会话表';

CREATE TABLE `code_helper_session_event` (
  `id` bigint NOT NULL COMMENT '主键',
  `ext` varchar(2000) DEFAULT NULL,
  `remark` varchar(1000) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `version` int DEFAULT NULL,
  `session_code` varchar(64) NOT NULL COMMENT '会话编码',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `event_sequence` bigint NOT NULL COMMENT '事件序号',
  `event_role` varchar(32) NOT NULL COMMENT '角色',
  `event_content` text COMMENT '事件内容',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code_helper_event_seq` (`session_code`, `tenant_id`, `event_sequence`),
  KEY `idx_code_helper_event_session` (`session_code`, `tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='代码助手会话事件表';

CREATE TABLE `code_helper_tool_log` (
  `id` bigint NOT NULL COMMENT '主键',
  `ext` varchar(2000) DEFAULT NULL,
  `remark` varchar(1000) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `version` int DEFAULT NULL,
  `session_code` varchar(64) NOT NULL COMMENT '会话编码',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `tool_name` varchar(64) NOT NULL COMMENT '工具名',
  `risk_level` varchar(16) DEFAULT NULL COMMENT '风险等级',
  `success_flag` tinyint(1) DEFAULT NULL COMMENT '是否成功',
  `request_json` text COMMENT '请求参数',
  `response_text` longtext COMMENT '响应内容',
  `duration_millis` bigint DEFAULT NULL COMMENT '耗时毫秒',
  `error_message` text COMMENT '错误信息',
  PRIMARY KEY (`id`),
  KEY `idx_code_helper_tool_session` (`session_code`, `tenant_id`),
  KEY `idx_code_helper_tool_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='代码助手工具执行日志表';
