<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.8</version>
        <relativePath/>
    </parent>

    <groupId>com.spring.ai</groupId>
    <artifactId>springAi</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>logging</module>
        <module>quickStart</module>
        <module>websocket</module>
        <module>sse</module>
        <module>common</module>
        <module>interceptors</module>
        <module>tools</module>
        <module>hooks</module>
        <module>skills</module>
        <module>prompt</module>
        <module>user</module>
        <module>agent</module>
        <module>core</module>
        <module>vectorStore</module>
        <module>a2a</module>
        <module>graph</module>
        <module>mcp</module>
        <module>opencv</module>
        <module>flowable</module>
        <module>link</module>
        <module>bigfile</module>
        <module>statistics</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <alibaba.ai.version>1.1.2.0</alibaba.ai.version>
        <alibaba.ai.extensions.version>1.1.2.1</alibaba.ai.extensions.version>
        <mybatis-plus.version>3.5.15</mybatis-plus.version>
        <velocity.version>2.4.1</velocity.version>
        <mysql.java>8.0.33</mysql.java>
        <druid.version>1.2.19</druid.version>
        <lombok.version>1.18.30</lombok.version>
        <jakarta.mail.version>2.0.1</jakarta.mail.version>
        <sa-token.version>1.45.0</sa-token.version>
        <pagehelper.version>2.1.0</pagehelper.version>
        <mysql-connector-java>3.0.3</mysql-connector-java>
        <sensitive-word.version>0.25.1</sensitive-word.version>
        <pdfbox.version>3.0.5</pdfbox.version>
        <poi.version>5.4.1</poi.version>
        <spring-ai.version>1.1.2</spring-ai.version>
        <spring-cloud.version>2025.0.0</spring-cloud.version>
        <spring-cloud-alibaba.version>2025.0.0.0</spring-cloud-alibaba.version>
        <nacos.version>3.1.0</nacos.version>
        <redisson.version>3.38.1</redisson.version>
        <onnxruntime.version>1.20.0</onnxruntime.version>
        <smartjavaai.version>1.0.19</smartjavaai.version>
        <smartjavaai.pytorch.jni.version>2.7.1-0.34.0</smartjavaai.pytorch.jni.version>
        <smartjavaai.pytorch.native.version>2.7.1</smartjavaai.pytorch.native.version>
        <smartjavaai.javacv.version>1.5.10</smartjavaai.javacv.version>
        <smartjavaai.ffmpeg.version>6.1.1-1.5.10</smartjavaai.ffmpeg.version>
        <smartjavaai.openblas.version>0.3.26-1.5.10</smartjavaai.openblas.version>
        <smartjavaai.opencv.native.version>4.9.0-1.5.10</smartjavaai.opencv.native.version>
        <face.javacv.classifier>windows-x86_64</face.javacv.classifier>
        <face.djl.classifier>win-x86_64</face.djl.classifier>
        <swagger.annotations.version>2.2.28</swagger.annotations.version>
        <graalvm.polyglot.version>24.1.0</graalvm.polyglot.version>
        <dashscope.sdk.version>2.22.16</dashscope.sdk.version>
        <spring-ai-alibaba-dashscope.version>1.1.2.2</spring-ai-alibaba-dashscope.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud.ai</groupId>
            <artifactId>spring-ai-alibaba-agent-framework</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>

        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>${pagehelper.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
            <version>${mybatis-plus.version}</version>
        </dependency>

        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
        </dependency>

        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>${redisson.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-bom</artifactId>
                <version>${alibaba.ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-extensions-bom</artifactId>
                <version>${alibaba.ai.extensions.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>cn.smartjavaai</groupId>
                <artifactId>smartjavaai-bom</artifactId>
                <version>${smartjavaai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-extension</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.microsoft.onnxruntime</groupId>
                <artifactId>onnxruntime</artifactId>
                <version>${onnxruntime.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.djl.pytorch</groupId>
                <artifactId>pytorch-jni</artifactId>
                <version>${smartjavaai.pytorch.jni.version}</version>
            </dependency>
            <dependency>
                <groupId>ai.djl.pytorch</groupId>
                <artifactId>pytorch-native-cpu</artifactId>
                <version>${smartjavaai.pytorch.native.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bytedeco</groupId>
                <artifactId>javacpp</artifactId>
                <version>${smartjavaai.javacv.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bytedeco</groupId>
                <artifactId>ffmpeg</artifactId>
                <version>${smartjavaai.ffmpeg.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bytedeco</groupId>
                <artifactId>openblas</artifactId>
                <version>${smartjavaai.openblas.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bytedeco</groupId>
                <artifactId>opencv</artifactId>
                <version>${smartjavaai.opencv.native.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.velocity</groupId>
                <artifactId>velocity-engine-core</artifactId>
                <version>${velocity.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations-jakarta</artifactId>
                <version>${swagger.annotations.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sun.mail</groupId>
                <artifactId>jakarta.mail</artifactId>
                <version>${jakarta.mail.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.houbb</groupId>
                <artifactId>sensitive-word</artifactId>
                <version>${sensitive-word.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox</artifactId>
                <version>${pdfbox.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>${poi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.graalvm.polyglot</groupId>
                <artifactId>polyglot</artifactId>
                <version>${graalvm.polyglot.version}</version>
            </dependency>
            <dependency>
                <groupId>org.graalvm.polyglot</groupId>
                <artifactId>python-community</artifactId>
                <version>${graalvm.polyglot.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>dashscope-sdk-java</artifactId>
                <version>${dashscope.sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-starter-dashscope</artifactId>
                <version>${spring-ai-alibaba-dashscope.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>nacos-client</artifactId>
                <version>${nacos.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>logging</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>quickStart</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>websocket</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>sse</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>interceptors</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>tools</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>hooks</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>skills</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>prompt</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>user</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>agent</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>vectorStore</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>a2a</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>graph</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>mcp</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>opencv</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>link</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>statistics</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.spring.ai</groupId>
                <artifactId>bigfile</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.smartjavaai</groupId>
                <artifactId>smartjavaai-bom</artifactId>
                <version>${smartjavaai.version}</version>
                <type>pom</type>
                <!-- 注意这里是import -->
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>face-platform-windows-x86_64</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <face.javacv.classifier>windows-x86_64</face.javacv.classifier>
                <face.djl.classifier>win-x86_64</face.djl.classifier>
            </properties>
        </profile>
        <profile>
            <id>face-platform-linux-x86_64</id>
            <properties>
                <face.javacv.classifier>linux-x86_64</face.javacv.classifier>
                <face.djl.classifier>linux-x86_64</face.djl.classifier>
            </properties>
        </profile>
        <profile>
            <id>face-platform-linux-aarch64</id>
            <properties>
                <face.javacv.classifier>linux-arm64</face.javacv.classifier>
                <face.djl.classifier>linux-aarch64</face.djl.classifier>
            </properties>
        </profile>
        <profile>
            <id>face-platform-macos-aarch64</id>
            <properties>
                <face.javacv.classifier>macosx-arm64</face.javacv.classifier>
                <face.djl.classifier>osx-aarch64</face.djl.classifier>
            </properties>
        </profile>
    </profiles>

</project>
