spring:
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  ai:
    dashscope:
      api-key: sk-c0351e8f4bb34a77bbf364c411932eeb
      embedding:
        options:
          model: text-embedding-v4
    openai:
      api-key: sk-5F4MCbuBCDQy4kPhTohZV7jt9A8wo8oCGUvn0C8VsmvdByVr
    deepseek:
      api-key: sk-417d47721a134518aa10a22666fa04b9
    anthropic:
      api-key: sk-417d47721a134518aa10a22666fa04b9
    zhipuai:
      api-key: sk-cNRM0AjYow5dAa5D2QHcZm857CSX048kgUnPr74bNHUpTjrQ
    model:
      embedding: dashscope
    vectorstore:
      redis:
        initialize-schema: true
        prefix: "vector:"
        index-name: my-vector-index
    alibaba:
      a2a:
        # 配置Nacos的地址和用户名密码
        nacos:
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          discovery:
            enabled: true   # 启用服务发现（查询其他 Agent）
          registry:
            enabled: true   # 启用服务注册（注册本地 Agent）
        # 配置A2A server的额外信息，如版本号，agentCard中的Skills等
        server:
          version: 1.0.0
          card:
            url: http://localhost:9999/a2a
            skills:
              - id: nacos-question-answer
                name: Nacos Question Answer
                description: Answer questions about Nacos.
                tags:
                  - Nacos
                examples:
                  - What is Nacos?
            icon-url: https://img.alicdn.com/imgextra/i4/O1CN01rW3vAB1FDWKSOiFf0_!!6000000000453-2-tps-204-40.png
            documentation-url: https://nacos.io
            provider:
              organization: Alibaba
              url: https://www.alibaba.com

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.ai

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

app:
  common:
    async:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 200
      keep-alive-seconds: 60
      thread-name-prefix: "common-async-"
  vector-store:
    default-top-k: 3
    chunk-size: 800
    min-chunk-size-chars: 350
    min-chunk-length-to-embed: 5
    max-num-chunks: 128
    keep-separator: true
    left-alignment: false
    number-of-top-pages-to-skip-before-delete: 0
    number-of-top-text-lines-to-delete: 0
    number-of-bottom-text-lines-to-delete: 0
    write-batch-size: 8
    parallel-write-enabled: false
    parallel-write-threshold: 64