<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.spring.ai</groupId>
        <artifactId>springAi</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>opencv</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>opencv</name>
    <description>图像处理模块</description>

    <properties>
        <java.version>21</java.version>
    </properties>
    <dependencies>
        <!--本地包-->
        <dependency>
            <groupId>com.spring.ai</groupId>
            <artifactId>common</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>



    </dependencies>

</project>
