CREATE TABLE IF NOT EXISTS `a2a_agent_card_record` (
  `id` bigint NOT NULL,
  `agent_code` varchar(128) NOT NULL,
  `agent_name` varchar(128) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `endpoint_url` varchar(500) NOT NULL,
  `protocol_version` varchar(32) DEFAULT '1.0',
  `transport_type` varchar(32) DEFAULT 'HTTP',
  `auth_type` varchar(32) DEFAULT 'NONE',
  `agent_status` varchar(32) DEFAULT 'ENABLED',
  `publish_status` varchar(32) DEFAULT 'DRAFT',
  `risk_level` varchar(32) DEFAULT 'MEDIUM',
  `trust_level` varchar(32) DEFAULT 'INTERNAL',
  `owner_team` varchar(128) DEFAULT NULL,
  `timeout_ms` int DEFAULT 10000,
  `rate_limit_qps` int DEFAULT 10,
  `success_rate_slo` int DEFAULT 99,
  `tenant_id` bigint NOT NULL,
  `deleted_flag` tinyint DEFAULT 0,
  `ext` longtext,
  `remark` varchar(500) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a2a_agent_code_tenant` (`tenant_id`,`agent_code`),
  KEY `idx_a2a_agent_publish` (`tenant_id`,`publish_status`,`agent_status`),
  KEY `idx_a2a_agent_owner` (`tenant_id`,`owner_team`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `a2a_route_record` (
  `id` bigint NOT NULL,
  `route_code` varchar(128) NOT NULL,
  `route_name` varchar(128) NOT NULL,
  `source_agent_code` varchar(128) DEFAULT NULL,
  `target_agent_code` varchar(128) NOT NULL,
  `task_type` varchar(128) NOT NULL,
  `route_status` varchar(32) DEFAULT 'ENABLED',
  `priority_no` int DEFAULT 100,
  `failover_enabled` tinyint DEFAULT 0,
  `fallback_agent_codes` varchar(500) DEFAULT NULL,
  `tenant_id` bigint NOT NULL,
  `ext` longtext,
  `remark` varchar(500) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a2a_route_code_tenant` (`tenant_id`,`route_code`),
  KEY `idx_a2a_route_match` (`tenant_id`,`route_status`,`task_type`,`source_agent_code`,`priority_no`),
  KEY `idx_a2a_route_target` (`tenant_id`,`target_agent_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `a2a_task_record` (
  `id` bigint NOT NULL,
  `task_code` varchar(64) NOT NULL,
  `task_type` varchar(128) NOT NULL,
  `source_agent_code` varchar(128) DEFAULT NULL,
  `target_agent_code` varchar(128) NOT NULL,
  `route_code` varchar(128) DEFAULT NULL,
  `task_status` varchar(32) NOT NULL,
  `request_payload_json` longtext,
  `response_payload_json` longtext,
  `failure_reason` varchar(500) DEFAULT NULL,
  `elapsed_ms` bigint DEFAULT NULL,
  `tenant_id` bigint NOT NULL,
  `ext` longtext,
  `remark` varchar(500) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a2a_task_code_tenant` (`tenant_id`,`task_code`),
  KEY `idx_a2a_task_query` (`tenant_id`,`task_type`,`task_status`,`create_time`),
  KEY `idx_a2a_task_agent` (`tenant_id`,`source_agent_code`,`target_agent_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `a2a_execution_log_record` (
  `id` bigint NOT NULL,
  `task_code` varchar(64) NOT NULL,
  `trace_id` varchar(64) NOT NULL,
  `source_agent_code` varchar(128) DEFAULT NULL,
  `target_agent_code` varchar(128) NOT NULL,
  `route_code` varchar(128) DEFAULT NULL,
  `event_type` varchar(64) NOT NULL,
  `execute_status` varchar(32) DEFAULT NULL,
  `attempt_no` int DEFAULT NULL,
  `retry_index` int DEFAULT NULL,
  `success_flag` tinyint DEFAULT 0,
  `elapsed_ms` bigint DEFAULT NULL,
  `request_payload_json` longtext,
  `response_payload_json` longtext,
  `failure_reason` varchar(500) DEFAULT NULL,
  `tenant_id` bigint NOT NULL,
  `ext` longtext,
  `remark` varchar(500) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_a2a_log_task` (`tenant_id`,`task_code`,`create_time`),
  KEY `idx_a2a_log_attempt` (`tenant_id`,`task_code`,`attempt_no`,`retry_index`),
  KEY `idx_a2a_log_trace` (`trace_id`),
  KEY `idx_a2a_log_agent` (`tenant_id`,`target_agent_code`,`success_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
