SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `model_provider_config`;
CREATE TABLE `model_provider_config` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `provider_config_code` varchar(64) NOT NULL COMMENT '提供商配置编码',
  `provider_enum` varchar(32) NOT NULL COMMENT '提供商枚举',
  `provider_name` varchar(128) NOT NULL COMMENT '提供商配置名称',
  `base_url` varchar(255) DEFAULT NULL COMMENT '自定义基础地址',
  `api_key_cipher_text` text COMMENT '加密后的 API Key',
  `organization_id` varchar(128) DEFAULT NULL COMMENT '组织标识',
  `default_headers_json` longtext COMMENT '默认请求头 JSON',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态 ENABLED/DISABLED',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `owner_user_id` bigint NOT NULL COMMENT '归属用户ID',
  `owner_user_name` varchar(64) DEFAULT NULL COMMENT '归属用户名称',
  `ext` longtext COMMENT '扩展字段',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_id` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_name` varchar(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_id` bigint DEFAULT NULL COMMENT '更新人ID',
  `update_name` varchar(64) DEFAULT NULL COMMENT '更新人名称',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_model_provider_config_code` (`tenant_id`, `provider_config_code`),
  UNIQUE KEY `uk_model_provider_config_name` (`tenant_id`, `provider_name`),
  KEY `idx_model_provider_status` (`tenant_id`, `status`, `provider_enum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型提供商配置表';

DROP TABLE IF EXISTS `model_definition`;
CREATE TABLE `model_definition` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `model_code` varchar(64) NOT NULL COMMENT '模型配置编码',
  `model_name` varchar(128) NOT NULL COMMENT '模型名称',
  `provider_config_id` bigint NOT NULL COMMENT '提供商配置ID',
  `provider_config_code` varchar(64) NOT NULL COMMENT '提供商配置编码',
  `provider_enum` varchar(32) NOT NULL COMMENT '提供商枚举',
  `model_type` varchar(32) NOT NULL DEFAULT 'CHAT' COMMENT '模型类型',
  `model_identifier` varchar(128) NOT NULL COMMENT '远端模型标识',
  `temperature` decimal(6,3) DEFAULT NULL COMMENT '温度',
  `top_p` decimal(6,3) DEFAULT NULL COMMENT 'Top P',
  `presence_penalty` decimal(6,3) DEFAULT NULL COMMENT 'Presence Penalty',
  `frequency_penalty` decimal(6,3) DEFAULT NULL COMMENT 'Frequency Penalty',
  `max_tokens` int DEFAULT NULL COMMENT '最大输出 Token',
  `context_window` int DEFAULT NULL COMMENT '上下文窗口',
  `rpm_limit` int DEFAULT NULL COMMENT '每分钟请求数',
  `tpm_limit` int DEFAULT NULL COMMENT '每分钟 Token 数',
  `timeout_ms` int DEFAULT NULL COMMENT '超时毫秒',
  `support_streaming` tinyint NOT NULL DEFAULT 1 COMMENT '是否支持流式输出',
  `support_tools` tinyint NOT NULL DEFAULT 1 COMMENT '是否支持工具调用',
  `support_vision` tinyint NOT NULL DEFAULT 0 COMMENT '是否支持视觉能力',
  `support_json_schema` tinyint NOT NULL DEFAULT 0 COMMENT '是否支持 JSON Schema',
  `is_default` tinyint NOT NULL DEFAULT 0 COMMENT '是否为默认模型',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态 ENABLED/DISABLED',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `owner_user_id` bigint NOT NULL COMMENT '归属用户ID',
  `owner_user_name` varchar(64) DEFAULT NULL COMMENT '归属用户名称',
  `advanced_config_json` longtext COMMENT '高级参数 JSON',
  `ext` longtext COMMENT '扩展字段',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_id` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_name` varchar(64) DEFAULT NULL COMMENT '创建人名称',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_id` bigint DEFAULT NULL COMMENT '更新人ID',
  `update_name` varchar(64) DEFAULT NULL COMMENT '更新人名称',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_model_definition_code` (`tenant_id`, `model_code`),
  UNIQUE KEY `uk_model_definition_name` (`tenant_id`, `model_name`),
  KEY `idx_model_definition_provider` (`tenant_id`, `provider_config_id`, `status`),
  KEY `idx_model_definition_default` (`tenant_id`, `provider_config_id`, `is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模型配置表';

SET FOREIGN_KEY_CHECKS = 1;
