DROP TABLE IF EXISTS `hook_agent_binding_record`;
DROP TABLE IF EXISTS `hook_execution_log_record`;
DROP TABLE IF EXISTS `hook_test_case_record`;
DROP TABLE IF EXISTS `hook_version_record`;
DROP TABLE IF EXISTS `hook_record`;

CREATE TABLE `hook_record`
(
    `id`                   BIGINT       NOT NULL COMMENT '主键ID',
    `hook_code`            VARCHAR(64)  NOT NULL COMMENT 'Hook 编码',
    `hook_name`            VARCHAR(128) NOT NULL COMMENT 'Hook 名称',
    `description`          VARCHAR(500)          DEFAULT NULL COMMENT 'Hook 描述',
    `hook_type`            VARCHAR(64)  NOT NULL COMMENT 'Hook 类型',
    `hook_stage`           VARCHAR(64)  NOT NULL COMMENT '执行阶段',
    `hook_status`          VARCHAR(32)  NOT NULL DEFAULT 'ENABLED' COMMENT '状态 ENABLED/DISABLED',
    `publish_status`       VARCHAR(32)  NOT NULL DEFAULT 'DRAFT' COMMENT '发布状态 DRAFT/PUBLISHED/OFFLINE',
    `risk_level`           VARCHAR(32)  NOT NULL DEFAULT 'LOW' COMMENT '风险等级 LOW/MEDIUM/HIGH/CRITICAL',
    `trigger_mode`         VARCHAR(32)  NOT NULL DEFAULT 'SYNC' COMMENT '触发模式',
    `fail_strategy`        VARCHAR(32)  NOT NULL DEFAULT 'CONTINUE' COMMENT '失败策略',
    `sort_weight`          INT          NOT NULL DEFAULT 100 COMMENT '排序权重',
    `timeout_ms`           INT          NOT NULL DEFAULT 10000 COMMENT '超时毫秒',
    `hot_update_enabled`   TINYINT      NOT NULL DEFAULT 0 COMMENT '是否开启热更新',
    `current_version_no`   INT          NOT NULL DEFAULT 1 COMMENT '当前版本号',
    `latest_version_no`    INT          NOT NULL DEFAULT 1 COMMENT '最新版本号',
    `published_version_no` INT                   DEFAULT NULL COMMENT '已发布版本号',
    `builtin_hook_key`     VARCHAR(64)           DEFAULT NULL COMMENT '内置模板键',
    `script_language`      VARCHAR(32)           DEFAULT NULL COMMENT '脚本语言',
    `deleted_flag`         TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    `tenant_id`            BIGINT       NOT NULL COMMENT '租户ID',
    `owner_user_id`        BIGINT       NOT NULL COMMENT '负责人用户ID',
    `owner_user_name`      VARCHAR(64)           DEFAULT NULL COMMENT '负责人名称',
    `ext`                  LONGTEXT              DEFAULT NULL COMMENT 'Hook 完整快照 JSON',
    `remark`               VARCHAR(255)          DEFAULT NULL COMMENT '备注',
    `create_id`            BIGINT                DEFAULT NULL COMMENT '创建人ID',
    `create_name`          VARCHAR(64)           DEFAULT NULL COMMENT '创建人名称',
    `create_time`          DATETIME              DEFAULT NULL COMMENT '创建时间',
    `update_id`            BIGINT                DEFAULT NULL COMMENT '更新人ID',
    `update_name`          VARCHAR(64)           DEFAULT NULL COMMENT '更新人名称',
    `update_time`          DATETIME              DEFAULT NULL COMMENT '更新时间',
    `version`              INT          NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_hook_record_code` (`tenant_id`, `hook_code`),
    KEY `idx_hook_record_status` (`tenant_id`, `hook_status`),
    KEY `idx_hook_record_publish` (`tenant_id`, `publish_status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT ='Hook 主表';

CREATE TABLE `hook_version_record`
(
    `id`                  BIGINT       NOT NULL COMMENT '主键ID',
    `hook_id`             BIGINT       NOT NULL COMMENT 'Hook ID',
    `hook_code`           VARCHAR(64)  NOT NULL COMMENT 'Hook 编码快照',
    `hook_name`           VARCHAR(128) NOT NULL COMMENT 'Hook 名称快照',
    `tenant_id`           BIGINT       NOT NULL COMMENT '租户ID',
    `version_no`          INT          NOT NULL COMMENT '版本号',
    `version_code`        VARCHAR(32)           DEFAULT NULL COMMENT '语义化版本',
    `version_description` VARCHAR(500)          DEFAULT NULL COMMENT '版本说明',
    `version_status`      VARCHAR(32)  NOT NULL COMMENT '版本状态 CURRENT/HISTORY/ROLLBACK',
    `publish_status`      VARCHAR(32)  NOT NULL COMMENT '发布状态',
    `snapshot_json`       LONGTEXT              DEFAULT NULL COMMENT '版本快照 JSON',
    `ext`                 TEXT                  DEFAULT NULL COMMENT '扩展字段',
    `remark`              VARCHAR(255)          DEFAULT NULL COMMENT '备注',
    `create_id`           BIGINT                DEFAULT NULL COMMENT '创建人ID',
    `create_name`         VARCHAR(64)           DEFAULT NULL COMMENT '创建人名称',
    `create_time`         DATETIME              DEFAULT NULL COMMENT '创建时间',
    `update_id`           BIGINT                DEFAULT NULL COMMENT '更新人ID',
    `update_name`         VARCHAR(64)           DEFAULT NULL COMMENT '更新人名称',
    `update_time`         DATETIME              DEFAULT NULL COMMENT '更新时间',
    `version`             INT          NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_hook_version_record` (`hook_id`, `version_no`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT ='Hook 版本表';

CREATE TABLE `hook_test_case_record`
(
    `id`                         BIGINT       NOT NULL COMMENT '主键ID',
    `hook_id`                    BIGINT       NOT NULL COMMENT 'Hook ID',
    `hook_code`                  VARCHAR(64)  NOT NULL COMMENT 'Hook 编码',
    `case_name`                  VARCHAR(128) NOT NULL COMMENT '测试用例名称',
    `input_payload_json`         LONGTEXT              DEFAULT NULL COMMENT '输入 JSON',
    `context_payload_json`       LONGTEXT              DEFAULT NULL COMMENT '上下文 JSON',
    `expected_success`           TINYINT      NOT NULL DEFAULT 1 COMMENT '期望是否成功',
    `expected_response_contains` VARCHAR(255)          DEFAULT NULL COMMENT '期望响应包含内容',
    `enabled`                    TINYINT      NOT NULL DEFAULT 1 COMMENT '是否启用',
    `last_run_status`            VARCHAR(32)           DEFAULT NULL COMMENT '最近运行状态',
    `last_run_duration_ms`       BIGINT                DEFAULT NULL COMMENT '最近运行耗时',
    `last_run_at`                DATETIME              DEFAULT NULL COMMENT '最近运行时间',
    `last_result_json`           LONGTEXT              DEFAULT NULL COMMENT '最近运行结果',
    `tenant_id`                  BIGINT       NOT NULL COMMENT '租户ID',
    `ext`                        TEXT                  DEFAULT NULL COMMENT '扩展字段',
    `remark`                     VARCHAR(255)          DEFAULT NULL COMMENT '备注',
    `create_id`                  BIGINT                DEFAULT NULL COMMENT '创建人ID',
    `create_name`                VARCHAR(64)           DEFAULT NULL COMMENT '创建人名称',
    `create_time`                DATETIME              DEFAULT NULL COMMENT '创建时间',
    `update_id`                  BIGINT                DEFAULT NULL COMMENT '更新人ID',
    `update_name`                VARCHAR(64)           DEFAULT NULL COMMENT '更新人名称',
    `update_time`                DATETIME              DEFAULT NULL COMMENT '更新时间',
    `version`                    INT          NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (`id`),
    KEY `idx_hook_test_case_hook` (`tenant_id`, `hook_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT ='Hook 测试用例表';

CREATE TABLE `hook_execution_log_record`
(
    `id`                    BIGINT      NOT NULL COMMENT '主键ID',
    `hook_id`               BIGINT               DEFAULT NULL COMMENT 'Hook ID',
    `hook_code`             VARCHAR(64)          DEFAULT NULL COMMENT 'Hook 编码',
    `hook_name`             VARCHAR(128)         DEFAULT NULL COMMENT 'Hook 名称',
    `tenant_id`             BIGINT      NOT NULL COMMENT '租户ID',
    `source_type`           VARCHAR(32) NOT NULL COMMENT '来源 DEBUG/TEST/RUNTIME',
    `source_id`             BIGINT               DEFAULT NULL COMMENT '来源对象ID',
    `trace_id`              VARCHAR(64)          DEFAULT NULL COMMENT '链路追踪ID',
    `agent_code`            VARCHAR(64)          DEFAULT NULL COMMENT '目标 Agent 编码',
    `session_code`          VARCHAR(64)          DEFAULT NULL COMMENT '会话编码',
    `request_payload_json`  LONGTEXT             DEFAULT NULL COMMENT '请求 JSON',
    `context_payload_json`  LONGTEXT             DEFAULT NULL COMMENT '上下文 JSON',
    `response_payload_json` LONGTEXT             DEFAULT NULL COMMENT '响应 JSON',
    `execute_status`        VARCHAR(32)          DEFAULT NULL COMMENT '执行状态',
    `success_flag`          TINYINT     NOT NULL DEFAULT 0 COMMENT '是否成功',
    `elapsed_ms`            BIGINT               DEFAULT NULL COMMENT '耗时毫秒',
    `failure_reason`        VARCHAR(500)         DEFAULT NULL COMMENT '失败原因',
    `operator_user_id`      BIGINT               DEFAULT NULL COMMENT '操作人ID',
    `operator_user_name`    VARCHAR(64)          DEFAULT NULL COMMENT '操作人名称',
    `ext`                   TEXT                 DEFAULT NULL COMMENT '扩展字段',
    `remark`                VARCHAR(255)         DEFAULT NULL COMMENT '备注',
    `create_id`             BIGINT               DEFAULT NULL COMMENT '创建人ID',
    `create_name`           VARCHAR(64)          DEFAULT NULL COMMENT '创建人名称',
    `create_time`           DATETIME             DEFAULT NULL COMMENT '创建时间',
    `update_id`             BIGINT               DEFAULT NULL COMMENT '更新人ID',
    `update_name`           VARCHAR(64)          DEFAULT NULL COMMENT '更新人名称',
    `update_time`           DATETIME             DEFAULT NULL COMMENT '更新时间',
    `version`               INT         NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (`id`),
    KEY `idx_hook_execution_log_hook` (`tenant_id`, `hook_id`),
    KEY `idx_hook_execution_log_source` (`tenant_id`, `source_type`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT ='Hook 执行日志表';

CREATE TABLE `hook_agent_binding_record`
(
    `id`                BIGINT       NOT NULL COMMENT '主键ID',
    `hook_id`           BIGINT       NOT NULL COMMENT 'Hook ID',
    `hook_code`         VARCHAR(64)  NOT NULL COMMENT 'Hook 编码',
    `binding_name`      VARCHAR(128) NOT NULL COMMENT '绑定名称',
    `binding_scope`     VARCHAR(32)  NOT NULL COMMENT '绑定范围',
    `target_agent_code` VARCHAR(64)           DEFAULT NULL COMMENT '目标 Agent 编码',
    `target_model_code` VARCHAR(64)           DEFAULT NULL COMMENT '目标模型编码',
    `environment_code`  VARCHAR(32)           DEFAULT NULL COMMENT '环境编码',
    `priority_no`       INT          NOT NULL DEFAULT 100 COMMENT '优先级',
    `enabled`           TINYINT      NOT NULL DEFAULT 1 COMMENT '是否启用',
    `tenant_id`         BIGINT       NOT NULL COMMENT '租户ID',
    `ext`               TEXT                  DEFAULT NULL COMMENT '扩展字段',
    `remark`            VARCHAR(255)          DEFAULT NULL COMMENT '备注',
    `create_id`         BIGINT                DEFAULT NULL COMMENT '创建人ID',
    `create_name`       VARCHAR(64)           DEFAULT NULL COMMENT '创建人名称',
    `create_time`       DATETIME              DEFAULT NULL COMMENT '创建时间',
    `update_id`         BIGINT                DEFAULT NULL COMMENT '更新人ID',
    `update_name`       VARCHAR(64)           DEFAULT NULL COMMENT '更新人名称',
    `update_time`       DATETIME              DEFAULT NULL COMMENT '更新时间',
    `version`           INT          NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (`id`),
    KEY `idx_hook_binding_hook` (`tenant_id`, `hook_id`),
    KEY `idx_hook_binding_agent` (`tenant_id`, `target_agent_code`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT ='Hook Agent 绑定表';
