CREATE TABLE IF NOT EXISTS `interceptor_record` (
  `id` bigint NOT NULL,
  `interceptor_code` varchar(128) NOT NULL,
  `interceptor_name` varchar(128) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `interceptor_type` varchar(64) NOT NULL,
  `interceptor_stage` varchar(64) NOT NULL,
  `interceptor_status` varchar(32) NOT NULL,
  `publish_status` varchar(32) NOT NULL,
  `risk_level` varchar(32) NOT NULL,
  `trigger_mode` varchar(32) NOT NULL,
  `fail_strategy` varchar(32) NOT NULL,
  `sort_weight` int DEFAULT 100,
  `timeout_ms` int DEFAULT 5000,
  `hot_update_enabled` tinyint DEFAULT 0,
  `current_version_no` int DEFAULT 1,
  `latest_version_no` int DEFAULT 1,
  `published_version_no` int DEFAULT NULL,
  `builtin_interceptor_key` varchar(128) DEFAULT NULL,
  `script_language` varchar(32) DEFAULT 'JAVA',
  `deleted_flag` tinyint DEFAULT 0,
  `tenant_id` bigint NOT NULL,
  `owner_user_id` bigint DEFAULT NULL,
  `owner_user_name` varchar(128) DEFAULT NULL,
  `ext` longtext,
  `remark` varchar(500) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_interceptor_code_tenant` (`tenant_id`,`interceptor_code`),
  KEY `idx_interceptor_stage_status` (`tenant_id`,`interceptor_stage`,`interceptor_status`),
  KEY `idx_interceptor_publish` (`tenant_id`,`publish_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `interceptor_version_record` (
  `id` bigint NOT NULL,
  `interceptor_id` bigint NOT NULL,
  `interceptor_code` varchar(128) NOT NULL,
  `interceptor_name` varchar(128) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `version_no` int NOT NULL,
  `version_code` varchar(128) DEFAULT NULL,
  `version_description` varchar(500) DEFAULT NULL,
  `version_status` varchar(32) NOT NULL,
  `publish_status` varchar(32) NOT NULL,
  `snapshot_json` longtext,
  `ext` longtext,
  `remark` varchar(500) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_interceptor_version` (`interceptor_id`,`tenant_id`,`version_no`),
  KEY `idx_interceptor_version_code` (`tenant_id`,`interceptor_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `interceptor_test_case_record` (
  `id` bigint NOT NULL,
  `interceptor_id` bigint NOT NULL,
  `interceptor_code` varchar(128) NOT NULL,
  `case_name` varchar(128) NOT NULL,
  `input_payload_json` longtext,
  `context_payload_json` longtext,
  `expected_success` tinyint DEFAULT 1,
  `expected_response_contains` varchar(255) DEFAULT NULL,
  `enabled` tinyint DEFAULT 1,
  `tenant_id` bigint NOT NULL,
  `last_run_status` varchar(32) DEFAULT NULL,
  `last_run_duration_ms` bigint DEFAULT NULL,
  `last_run_at` datetime DEFAULT NULL,
  `last_result_json` longtext,
  `ext` longtext,
  `remark` varchar(500) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_interceptor_test_case` (`tenant_id`,`interceptor_id`,`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `interceptor_execution_log_record` (
  `id` bigint NOT NULL,
  `interceptor_id` bigint NOT NULL,
  `interceptor_code` varchar(128) NOT NULL,
  `interceptor_name` varchar(128) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_id` bigint DEFAULT NULL,
  `trace_id` varchar(64) DEFAULT NULL,
  `agent_code` varchar(128) DEFAULT NULL,
  `session_code` varchar(128) DEFAULT NULL,
  `request_payload_json` longtext,
  `context_payload_json` longtext,
  `response_payload_json` longtext,
  `execute_status` varchar(32) NOT NULL,
  `success_flag` tinyint DEFAULT 0,
  `elapsed_ms` bigint DEFAULT NULL,
  `failure_reason` varchar(500) DEFAULT NULL,
  `operator_user_id` bigint DEFAULT NULL,
  `operator_user_name` varchar(128) DEFAULT NULL,
  `ext` longtext,
  `remark` varchar(500) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_interceptor_log_query` (`tenant_id`,`interceptor_id`,`source_type`,`success_flag`),
  KEY `idx_interceptor_trace` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `interceptor_agent_binding_record` (
  `id` bigint NOT NULL,
  `interceptor_id` bigint NOT NULL,
  `interceptor_code` varchar(128) NOT NULL,
  `binding_name` varchar(128) NOT NULL,
  `binding_scope` varchar(32) NOT NULL,
  `target_agent_code` varchar(128) DEFAULT NULL,
  `target_model_code` varchar(128) DEFAULT NULL,
  `environment_code` varchar(64) DEFAULT NULL,
  `priority_no` int DEFAULT 100,
  `enabled` tinyint DEFAULT 1,
  `tenant_id` bigint NOT NULL,
  `ext` longtext,
  `remark` varchar(500) DEFAULT NULL,
  `create_id` bigint DEFAULT NULL,
  `create_name` varchar(128) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_id` bigint DEFAULT NULL,
  `update_name` varchar(128) DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_interceptor_binding_scope` (`tenant_id`,`interceptor_id`,`binding_scope`,`enabled`),
  KEY `idx_interceptor_binding_agent` (`tenant_id`,`target_agent_code`,`environment_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
