-- 短链接模块表结构
CREATE TABLE IF NOT EXISTS `short_link_record` (
  `id` bigint NOT NULL COMMENT '主键',
  `short_code` varchar(64) NOT NULL COMMENT '短码',
  `short_url` varchar(512) NOT NULL COMMENT '完整短链接',
  `long_url` varchar(2048) NOT NULL COMMENT '原始长链接',
  `title` varchar(128) DEFAULT NULL COMMENT '标题',
  `description` varchar(512) DEFAULT NULL COMMENT '描述',
  `domain` varchar(255) DEFAULT NULL COMMENT '原始域名',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态：ENABLED/DISABLED',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `total_visit_count` bigint NOT NULL DEFAULT 0 COMMENT '访问次数',
  `unique_visitor_count` bigint NOT NULL DEFAULT 0 COMMENT '访问人数',
  `unique_ip_count` bigint NOT NULL DEFAULT 0 COMMENT '独立 IP 数',
  `last_access_time` datetime DEFAULT NULL COMMENT '最后访问时间',
  `deleted_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标识',
  `ext` text DEFAULT NULL COMMENT '扩展字段',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `create_id` bigint DEFAULT NULL COMMENT '创建人 ID',
  `create_name` varchar(128) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_id` bigint DEFAULT NULL COMMENT '更新人 ID',
  `update_name` varchar(128) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `version` int DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_short_link_code` (`short_code`),
  KEY `idx_short_link_long_url` (`long_url`(255)),
  KEY `idx_short_link_status` (`status`, `deleted_flag`),
  KEY `idx_short_link_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='短链接主表';

CREATE TABLE IF NOT EXISTS `short_link_access_log_record` (
  `id` bigint NOT NULL COMMENT '主键',
  `short_code` varchar(64) NOT NULL COMMENT '短码',
  `long_url` varchar(2048) DEFAULT NULL COMMENT '原始长链接',
  `visitor_id` varchar(128) DEFAULT NULL COMMENT '访问者标识',
  `ip_address` varchar(64) DEFAULT NULL COMMENT '访问 IP',
  `user_agent` varchar(512) DEFAULT NULL COMMENT 'User-Agent',
  `referer` varchar(512) DEFAULT NULL COMMENT '来源页面',
  `access_time` datetime NOT NULL COMMENT '访问时间',
  `success_flag` tinyint NOT NULL DEFAULT 1 COMMENT '是否成功',
  `fail_reason` varchar(255) DEFAULT NULL COMMENT '失败原因',
  `ext` text DEFAULT NULL COMMENT '扩展字段',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `create_id` bigint DEFAULT NULL COMMENT '创建人 ID',
  `create_name` varchar(128) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_id` bigint DEFAULT NULL COMMENT '更新人 ID',
  `update_name` varchar(128) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `version` int DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (`id`),
  KEY `idx_short_link_log_code_time` (`short_code`, `access_time`),
  KEY `idx_short_link_log_ip` (`ip_address`),
  KEY `idx_short_link_log_visitor` (`visitor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='短链接访问日志表';
