<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.spring.ai</groupId>
        <artifactId>springAi</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>a2a</artifactId>
    <name>a2a</name>
    <description>a2a module</description>

    <properties>
        <java.version>21</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud.ai</groupId>
            <artifactId>spring-ai-alibaba-starter-a2a-nacos</artifactId>
        </dependency>

        <dependency>
            <groupId>com.spring.ai</groupId>
            <artifactId>common</artifactId>
        </dependency>

        <dependency>
            <groupId>com.spring.ai</groupId>
            <artifactId>core</artifactId>
        </dependency>
    </dependencies>
</project>
